channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.1.1
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==1.26.0
  - psutil==7.0.0
  - scikit-learn==1.3.0
  - scipy==1.16.0
name: mlflow-env
